# Generated by Django 4.2.7 on 2023-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default_pfp.jpg', null=True, upload_to='profiles/'),
        ),
    ]
