# Generated by Django 4.2.7 on 2023-11-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='xp_amount',
            field=models.IntegerField(default=0),
        ),
    ]
