# Generated by Django 4.2.7 on 2023-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='idhtml',
            field=models.CharField(default='123', editable=False, max_length=10),
        ),
    ]
